### ISSUE TITLE
PizzaHut.com geo redirect

### ISSUE THREAD

**Issue by Tiffys** [salarcode/SmartProxy#152]
I live in the US and use a Canadian "VPN". In my SmartProxy settings I have pizzahut.com and pizzahut.ca set up with rule type "search domain and subdomain" with rule source domain as "pizzahut.com" and "pizzahut.ca" respectively, set to my proxy server (SSH via a seedbox based in Canada), action set to "whitelist (no proxy)" and despite that, when I try to visit pizzahut.com with SmartProxy enabled it tries to redirect to pizzahut.ca and can't load the site. I can only access pizzahut's site if I disable SmartProxy (direct (no proxy)). I'm not sure at what level pizzahut.com has geoblocking but it seems it may not be from pizzahut.com itself but some script from another source they use. But you'd think when one of those whitelisted domains are loaded anything it attempts to load should be off the proxy as well. So if that's the case then something must be wrong.

**Comment by salarcode** [comment]
The roots of the issue you're facing can be because of different reasons:
1- There is another request to other domain than pizzahut that is checking the Geolocation, like Amazon services. To test if this is the case try using Always Enabled mode.
2- There are cookies/local storage data of the first ever visit is stored in your browser. Try removing the site data by Remove Site Data tool in your browser and try again with Always Enabled.
3- You're actually logged in and your personal account has location stored somewhere (even hidden one). Can't do much, maybe try a new account while Always Enabled is selected.

Also what is your browser? If its Chrome then chrome can suffer from multidomain issue as in number 1.

**Comment by Tiffys** [comment]
> The roots of the issue you're facing can be because of different reasons:
> 1- There is another request to other domain than pizzahut that is checking the Geolocation, like Amazon services. To test if this is the case try using Always Enabled mode.
> 2- There are cookies/local storage data of the first ever visit is stored in your browser. Try removing the site data by Remove Site Data tool in your browser and try again with Always Enabled.
> 3- You're actually logged in and your personal account has location stored somewhere (even hidden one). Can't do much here, maybe try a new account while Always Enabled is selected.
> 
> Also what is your browser? If its Chrome then chrome can suffer from multidomain issue as in number 1.

It's most likely thingy 1 but I'm on Always Enable already, I just use a whitelist to allow a certain select few sites. It's not a cookies problem since my first visit to the site was in the US which is where it should be loading to. And I am logged into my account, but it's located in the appropriate location.

The browser is Chrome.

**Comment by salarcode** [comment]
Try Proxyable Resources it will help identifying the suspicious domain.

**Comment by Tiffys** [comment]
> Try Proxyable Resources it will help identifying the suspicious domain.

I whitelisted every possible thing on pizzahut.com and pizzahut.ca and it still happens.
