### ISSUE TITLE
多个代理扩展的时候能切换给其他扩展，智能代理的时候希望能通过图标看出是否有使用代理

### ISSUE THREAD

**Issue by Wirili** [salarcode/SmartProxy#153]
多个代理扩展的时候能切换给其他扩展，智能代理的时候希望能通过图标看出是否有使用代理

**Comment by salarcode** [comment]
Hi, can you please type in English?

**Comment by mraandtux** [comment]
Although I am a native Chinese speaker, but I still don't get it. What is "Switching to other proxy addons when multiple proxy addons is used", you mean switching to other proxies? That's on the drop menu; by you mean "to see if any site is access through proxy via the icon", that's a feature request, through I'd love to see the latter becoming a feature on Smart Proxy since it's a legit feature on [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega), which haven't been updated since '18.

**Comment by Wirili** [comment]
yes ,like SwitchyOmega 
![O900U0{TKBE9FKBJ M%6`F4](https://user-images.githubusercontent.com/16308800/99263973-d889a880-285a-11eb-8549-b184c7608d12.png)
