### ISSUE TITLE
Пропуск ссылок из списка мимо прокси при открытии браузера

### ISSUE THREAD

**Issue by Sanders-and-Sanders** [salarcode/SmartProxy#169]
Если браузер был закрыт, то ссылка из списка не открывается через прокси, а идёт напрямую. Чтобы ссылка из списка пошла через прокси необходимо чтобы либо браузер был открыт, либо обновить страницу. Такое поведение может создавать утечку в сторону провайдера. Вообще это я обнаружил на 88 версии впервые, так как до этого было всё отлично. Сославшись на возможный недостаток моей сборки установил 89 beta - результат такой-же.
Думаю из видео будет понятно как это происходит и простите за мой русский. Я понимаю что тут желательно писать на English. Спасибо.
https://drive.google.com/file/d/1d0VkCthitjTKPEvcWw7axKyiG8Lpf21q/view?usp=sharing

**Comment by salarcode** [comment]
This is what understood from your video and your comment (with google translate):
Normally proxy rules apply correctly and everything work fine while browser is open, but when Browser is closed and you open a link that directly opens a page in  browser, the proxy rules doesn't work you have to refresh the page, then they work.

Here is the possible explanation:
This happens because of how browser loads extensions, it is possible that browser has started to load the page before loading SmartProxy so there is no extension at that split of a second.
Second possible thing is that it takes a little time for data to be retrieved from extensions storage. This data contains rules and servers definitions. While data is not available yet, browser makes a request and since there is no rule yet smartproxy bypasses the request.

Here is a possible workaround:
Try to disable `settings syncing` this could be one cause of delays to load extension data.
Also try to disable/remove `subscriptions` if you have any which can be another cause of delays.

I'm leaving this issue open to monitor any changes, will need to investigate more.
