### ISSUE TITLE
Request to add new features

### ISSUE THREAD

**Issue by cool-delete** [salarcode/SmartProxy#176]
Support importing pac exported from chrome SwitchyOmega

like this

```pac
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+auto switch", {
    "+auto switch": function(url, host, scheme) {
        "use strict";
        if (/(?:^|\.)wget\.es$/.test(host)) return "+ssr";
        if (/(?:^|\.)shiki\.hu$/.test(host)) return "+ssr";
        if (/(?:^|\.)bookwalker\.com\.tw$/.test(host)) return "+ssr";
        if (/(?:^|\.)books\.com\.tw$/.test(host)) return "+ssr";
        if (/(?:^|\.)google\.com$/.test(host)) return "+ssr";
```

In addition, right-click a URL hyperlink to add a new item in the menu: "add this link to the proxy list: whitelist"

**Comment by salarcode** [comment]
I don't understand this if you're going to use PAC why you use any browser addons then?

**Comment by cool-delete** [comment]
> 如果您要使用PAC，我不明白这一点，那么为什么要使用任何浏览器插件呢？

Browser addons  can be refined management. It is troublesome to simply edit pac to select a certain URL, right?

**Comment by salarcode** [comment]
PAC format will not be supported, but Switchy one will #175

**Comment by cool-delete** [comment]
thx！！
>In addition, right-click a URL hyperlink to add a new item in the menu: "add this link to the proxy list: whitelist"

Can you add this features?

**Comment by salarcode** [comment]
Yep we can capture it under #178

**Comment by salarcode** [comment]
Switchy is added in v0.9.9

**Comment by zzzgit** [comment]
> Switchy is added in v0.9.9

界面中都沒有啟用這個功能。SwitchyOmega

**Comment by salarcode** [comment]
> > Switchy is added in v0.9.9
> 
> 界面中都沒有啟用這個功能。SwitchyOmega

In English please

**Comment by InvisibleRain** [comment]
There's a workaround for Firefox, in case you want to combine a PAC with some manual settings. 

1. Type `about:config` in the address bar 
2. Set `network.proxy.autoconfig_url` to the link to your PAC
3.  Set `network.proxy.type` to 2

Very useful for circumventing censorship through public proxy-autoconfigs while also whitelisting some websites.
Verified working on Both Desktop Firefox and Fennec F-Droid.

**Comment by zyf0330** [comment]
> I don't understand this if you're going to use PAC why you use any browser addons then?

@salarcode Did you mean that user should use PAC proxy feature provided by OS, like this on the KDE?
![image](https://github.com/salarcode/SmartProxy/assets/11958657/a521953b-f412-4c7d-893b-ab324da30289)
If you did, I want to say that I just want the PAC is effect in the browser instead of the whole OS.

Another aspect is that the PAC is a widely used standard across browsers and OSes, so I think it is better that custom rule format.

Actually, what I need is a convenient tool to switch between my different proxy servers. They have different functions. One socks is used daily, one socks is used for special network access, one pac is used at work, one is a backup server, etc. And I write different type rules behind them.

So still hope to support PAC as a kind of proxy server.
