### ISSUE TITLE
[FEATURE REQUEST] Smart routing by HTTP codes (e.g 403)

### ISSUE THREAD

**Issue by hummblebee** [salarcode/SmartProxy#188]
Hi

I'm not familiar with how browsers and the web work so I'm not sure if this requests are possible technically but I was wondering if you could implement a smart rule-applying feature that sniffs response headers and re-routes requests that were responded by a [HTTP 403 error code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) which is usually the websites we have to manually inspect and add to rules.

Another issue I witnessed on my heavily censored network is that blocked websites are timed-out if they do not return with a 403 error! Having the ability to set a time-out threshold (e.g: 3000 ms) for responses and re-routing them through the proxy if they exceed this maximum threshold would be great.

Good work so far, thank you!

**Comment by salarcode** [comment]
There is a feature called Error Detection which does exactly what you have mentioned, detected failures and suggests adding proxy rules by user.
Because it cannot be 100% accurate this can't be made automated.
![image](https://user-images.githubusercontent.com/1272095/131479420-feec96ec-b487-4bd8-bf1f-d00ed1816ba7.png)
