### ISSUE TITLE
System settings as one of the Proxy servers

### ISSUE THREAD

**Issue by jimo4242** [salarcode/SmartProxy#231]
Hello, I would like to have the System settings as one of the possible proxy servers that can be used in the rules.
And if possible, also the "autodetect" option of the FF original proxy dialogue as another "proxy server" that can be used in rules - but this is not that crucial.

What would be nice for my usecase is "system proxy" as default setting and then add sites with "disable proxy" in SmartProxy that would have direct connection to the Internet.

Thank you for consideration.

**Comment by salarcode** [comment]
For these reasons we can't do this:

- Configuring System proxy from rule is not possible in Chrome. And majority of users are from Chromium browsers.
- Also that is limited in Firefox and it requires Private Browsing permission manually enabled by user.
- Instead of setting proxy on system, why not use the extension for that, it defeats the purpose of the extension.
