### ISSUE TITLE
 Version 1.0 beta testers wanted 📣

### ISSUE THREAD

**Issue by salarcode** [salarcode/SmartProxy#236]
Hi all, I'm finishing off version V1 and in need of your eyes and brains 🧟🧠 for testing

[The alpha testing thread is here.](https://github.com/salarcode/SmartProxy/issues/213)

## Before start testing, here is how to prepare:

- Create a full back-up of your settings of your current SmartProxy
- Disable SmartProxy stable version v0.9.x
- [Download the Zips from here](https://github.com/salarcode/SmartProxy/releases/tag/v1.0-beta.x) and Unzip it
- Install the new temporary version
  - [For Firefox use this guide](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)
  - [For Chrome use this one](https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked)
  - [For Thunderbird use this one](https://arndissler.net/supercharge-your-thunderbird-extension-debugging/)
- You can restore old version backups now

### What to test
- Please test the following list of features
- Test whatever other features that are important to you
- Please report the bugs in this thread
 
## To be tested features

1. - [x]  Smart Profiles
4. - [x] Support for Firefox
3. - [x]  Profile for SmartProxy mode.
4. - [x]  Profile for Always Enabled mode.
5. - [x]  Profile for Ignore Failure Rules.
6. - [x]  Different Proxy Server per profile.
7. - [x]  Display the applied rule to the tab in tooltip.
8. - [x]  Theme support.
9. - [x]  Theme auto switch support
10. - [x]  Bootstrap 5 UI
11. - [x]  Seamless migration from v0.9.x
12. - [x]  Back-up/Restore
13. - [x]  Factory Reset option
14. - [x]  Support for Chrome
15. - [x]  Move the help center to [Wiki](https://github.com/salarcode/SmartProxy/wiki)
16. - [x]  Link to relevant help docs from pages
17. - [x] Support for Thunderbird 
18. - [x] Support for Google extensions Manifest V3
19. - [x] Forcing always enabled in Private Browsing #208 
20. - [x] Firefox for Android support
21. - [x] Firefox for Android installation guide docs
22. - [x] Refresh active tab when profile or proxy change

## Not completed yet

1. - [ ]  Complete the help docs

**Comment by salarcode** [comment]
V1.0-beta.1 notes:

- Refresh active tab when profile or proxy change
- Settings grid resizing issue fixed

**Comment by fred0r** [comment]
using this beta for some hours now and its really annoying to reinstall it after every restart of firefox.
could you please provide a 'beta-temp'.xpi ?

**Comment by fred0r** [comment]
using this beta for some hours now and it works a lot better than the 0.9.x.
the need to reinstall it after every restart of firefox is really annoying - could you please provide a 'beta-temp'.xpi ?

**Comment by salarcode** [comment]
Thank you all for testing, we need this testing phase to test all features including new and old ones, so this might take some time

**Comment by fred0r** [comment]
> we need this testing phase to test all features including new and old ones

i understand that there shouldnt be a beta in the mozilla-addons, but how about a temporary *.xpi for firefox, which is only downloadable from this github-repository?

**Comment by microka** [comment]
I test SmartProxy-v1.0-beta.1-Chrome-ManifestV3.zip on Chrome 107.0.5304.107 Stable for Windows, it works. But i wonder to know #127 this feature is still in progress?

**Comment by fonlan** [comment]
I tried in SmartProxy-v1.0-beta.1-Chrome-ManifestV3 with Edge. 
When I import full backup from old release it success. But after I close the SmartProxy option tab and re-open it, all proxy server and rule were lost.
So I tried create brandnew configuration with beta version. But it's still the same. After close/re-open option tab all configuration lost.

**Comment by mikamidd** [comment]
I'm currently using ProxySwitchy and decided to check out SmartProxy. Took a quick look at the stable and beta builds on Edge Dev 109.0.1495.2 on Win 10.  Mostly no issues but some things weren't working right, and a few suggestions in no particular order.

- Custom rules can't be imported. On import an error pops up:

> DataTables warning: table id=grdRules - Requested unknown parameter 'ruleTypeName' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

- Not sure if it was removed but "Proxyable Resources" menu is nowhere to be found. Tried both manifest v2 and v3 on Edge Dev and Edge Stable. If this wasn't discontinued, make it easier to see failed requests by making those appear in different color or add a "failed" column, right now it's impossible to see a difference between fail/success requests. Maybe a button to show/hide failed requests only or some kind of grouping by domain name.

- Detect request failures can be pretty unreliable, with failed requests disappearing and reappearing in the list. Possibly a design limitation because even actual failures and 403's can disappear from the list and it happens in 0.9.12 as well as ProxySwitchy, but Switchy seems a bit more reliable.

- Server list and rule list table UI should be expanded to accommodate 10 items at once, as "show X entries" indicates. Currently only 6 and a half items are visible before the scrollbar appears. ![rules](https://user-images.githubusercontent.com/66689934/203123502-2de23693-bfad-4fac-a25e-71550527029c.jpg)

- Consider adding a button to quickly enable/disable a rule without having to go through the Edit menu.

- If the UI allows it, make it possible to reorganize the server/rules list by dragging and dropping items similar to ProxySwitchy: [example.webm](https://user-images.githubusercontent.com/66689934/203124687-945fa65c-a790-4183-9fd2-2802a26e9c59.webm)

- In addition to sorting, make the server list in the popup and extension options respect the sort order or at least sort by name instead of date. An example of servers added in the following order: A B D E C 
![order](https://user-images.githubusercontent.com/66689934/203126023-c81862e9-0d77-46c6-80da-854982d63cf7.jpg)

**Comment by salarcode** [comment]
> I'm currently using ProxySwitchy and decided to check out SmartProxy. Took a quick look at the stable and beta builds on Edge Dev 109.0.1495.2 on Win 10. Mostly no issues but some things weren't working right, and a few suggestions in no particular order.

Thanks for your testing, you have very good suggestions.
While I'll definitely fix the issues, for UI tweaks I might delay them until next release after v1.0. I'm a little short on free time.

**Comment by salarcode** [comment]
> I test SmartProxy-v1.0-beta.1-Chrome-ManifestV3.zip on Chrome 107.0.5304.107 Stable for Windows, it works. But i wonder to know #127 this feature is still in progress?

Sorry no it is not in the scope of this version

**Comment by salarcode** [comment]
V1.0 beta 2 is out; the release notes:

* This is the last beta, next is the release 🎉 
* Proxy Servers can be reordered now
* Subscriptions last attempt status are accessible from their grid
* Fix: settings page fails to load config on the first try in Google Chrome 
* Fix for #243 Multiple rule subscriptions
* Mobile UI grids fixes
* Fix: Syncing issues when subscriptions are enabled

**Comment by salarcode** [comment]
> Oh, this addon could be installed on mobile devices? (Is the functionality --- "installing any addon on mobile", only available in Firefox nightly?)
Yes Firefox nightly is the only one allowing this installation on mobile devices
Here is how https://github.com/salarcode/SmartProxy/wiki/Install-on-Firefox-Android

**Comment by bytemain** [comment]
![CleanShot 2023-01-07 at 16 57 44@2x](https://user-images.githubusercontent.com/13938334/211142532-e55f448d-15d8-46e2-829c-f884b9e5afa4.png)

![CleanShot 2023-01-07 at 17 00 28@2x](https://user-images.githubusercontent.com/13938334/211142634-0d687ef3-3247-4493-a2f2-9a2ab5370d0c.png)

colors of icon on the toolbar and color of icon on the popup are different colors.

in the settings page, `smart` option is green, in toolbar, `smart` is blue.

**Comment by fred0r** [comment]
> > Oh, this addon could be installed on mobile devices? (Is the functionality --- "installing any addon on mobile", only available in Firefox nightly?)
> 
> Yes Firefox nightly is the only one allowing this installation on mobile devices Here is how https://github.com/salarcode/SmartProxy/wiki/Install-on-Firefox-Android

pls keep in mind that socks4/ 5-credentials are not encrypted.

**Comment by salarcode** [comment]
Version 1.0 has just release, you can get it after it is available by the browsers markets.

Thanks everyone for helping and testing.

Closing this thread. Please open a new one for bugs and support.

**Comment by fred0r** [comment]
thx for your work.
