### ISSUE TITLE
Smart Profiles when DomainSubdomain contains port

### ISSUE THREAD

**Issue by fred0r** [salarcode/SmartProxy#238]
using 1.0-beta on firefox-nightly and have problems accessing sites which are configured  in Smart Profiles with the DomainSubdomain rule, but dont run on the protocol default port.
for example i've configured `DomainSubdomain` for source `localhost` and rule `localhost` and cant connect to http://localhost:631/ (cups).
same happens with `MatchPatternHost`, when a 'non protocol default port' is used.
in my view it should make no difference which port is connected to, as long the configured rule matches.
to me it somehow sounds like https://github.com/salarcode/SmartProxy/issues/50 - but without the need to add each ports manually.

**Comment by salarcode** [comment]
Thanks, I will look into this.

**Comment by salarcode** [comment]
Sorry I didn't read the question carefully the first time otherwise I would give you the answer then.
`DomainSubdomain` will match domain and subdomain, so the port number same as domain name should exactly match.
Here are some examples

Rule: `localhost` 
matches: `http://localhost/` and `http://sub.localhost/` and `http://localhost:80/`
doesn't match `http://localhost:631/`

Rule `localhost:631`
matches: `http://localhost:631/` and `http://sub.localhost:631/`
doesn't match `http://localhost/` and `http://localhost:80/`

What you need is to use `Host regex` with this rule `localhost(\:\d*)?` 
this will match `http://localhost:80/` , `http://localhost:80/` and `http://localhost:631/`
