### ISSUE TITLE
Add subscriptions to AlwaysEnabled profile

### ISSUE THREAD

**Issue by Rongronggg9** [salarcode/SmartProxy#274]
**Is your feature request related to a problem? Please describe.**
In SmartProxy v0.x, I use a [technique to run SmartProxy with my allowlist subscription](https://github.com/Rongronggg9/chinalist#smartproxy) (proxy all but bypass if matches subscribed rules). The subscription is a list of websites that do not require a proxy (contrary to gfwlist).
After upgrading to v1.0, I can no longer mix "proxy all" with "bypass if matches subscribed rules". If I select "Smart Rules", a match-all rule will always override bypass rules in the subscription. If I select "Always Enabled", I cannot subscribe to rule lists.

**Describe the solution you'd like**
In "Smart Rules" mode, users can select the default proxy behavior: proxy all or bypass all.

**Describe alternatives you've considered**
In "Always Enabled" mode, users can subscribe to rule lists.

**Additional context**
SwitchyOmega has configurable default behavior for smart mode.

**Comment by salarcode** [comment]
Originally `Always Enabled` was supposed to have subscriptions too, but it didn't make it to final version because of my limited time to polish it.
You might be able to still use it as the code is there, its just hidden.
It`s a hidden feature and i'm not sure this is going to work or not.
I see you are dev as well so this should be easy for you.

* Create a backup
* Makes below changes to the json
* Restore the backup
* Restart browser

![image](https://user-images.githubusercontent.com/1272095/226819939-65bdda2a-c9d5-48db-a845-ce1e0fa797b3.png)

**Comment by salarcode** [comment]
Of course this is a temporarily workaround if you really want the feature.
This is a good reminder for me have this feature in my radar

**Comment by salarcode** [comment]
This is released with version 1.1
