### ISSUE TITLE
UDP clarity in documentation

### ISSUE THREAD

**Issue by sb23424** [salarcode/SmartProxy#284]
I'm pretty sure this extension covers UDP traffic (mostly thinking of webrtc and http3).
I've tried a few leak testing sites, and everything *looks* good, but I think that can be misleading.

I know with some older proxies, UDP was an issue.

I'd like to see it addressed specifically in the documentation, or at least in a response here.

**Comment by salarcode** [comment]
SmartProxy or any other extension doesn't have control on low level protocols like TCP/UDP.
All the requests are processed as presented by the browser and since browsers support Http3 and webrtc this extension also supports them automatically. 

More info:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/RequestFilter
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns
