### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by amirnaby** [salarcode/SmartProxy#322]
### Description

I uncheck "enable shortcuts" to disable it, it is disabled but still that shortcuts don't act their defaults and I should disable addon to restore shortcuts default acts.
Please fix it or just change this shortcut:
**Switch to 'Smart Proxy' mode: Shortcut Keys : Ctrl+Shift+2**
In some languages like Persian this shortcut is used for non-breaking space.

### Steps to Reproduce

1. Enable addon
2. Uncheck enable shortcuts
3. Change language to Persian
4. Press ctrl+shift+2 and see the default act that is non-breaking space in Persian doesn't work! 

### Which browsers did you test this on?

Chrome

### Affected browser versions

Chrome 118

### Affected SmartProxy versions

1.3.1

### Screenshots of the problems or steps to reproduce

![image](https://github.com/salarcode/SmartProxy/assets/17646860/9f3be1c3-85dd-4537-9031-9756f1ac484d)
![image](https://github.com/salarcode/SmartProxy/assets/17646860/5c94f22f-50ac-404b-afed-628579346c65)

**Comment by salarcode** [comment]
Shortcuts are controlled by browsers and in the browser extensions settings you can assign a new shortcuts.
Any change to the default shortcut will affect all users and because Iran users are not in top 5 countries, I've decided not to change it.
![image](https://github.com/salarcode/SmartProxy/assets/1272095/f05a3416-704f-4e3c-bab0-0ead1c60cb2e)
