### ISSUE TITLE
Use Profile Proxy vs Use Active Proxy

### ISSUE THREAD

**Issue by LLKoder** [salarcode/SmartProxy#408]
### Description

I don't understand what's the difference between Use Profile Proxy and Use Active Proxy proxy servers in Smart Profile. Examlpe pls...

Thanks in advance.

**Comment by salarcode** [comment]
Sorry for delay,

![image](https://github.com/user-attachments/assets/21409c06-2384-4e3a-930c-fc9e659ddd7f)

Here is what they mean:
(1) is the Active Proxy and (2) is the Profile Proxy.
Now because the value of (2) is Use Default Proxy server it is actually pointing to (1) and as a result both have the same value with this configuration. 
You can change profile proxy as you desire and point rules to that.

**Comment by whenov** [comment]
Since the term "Active Proxy" does not appear in either the config page or the context menu, should it be renamed to "Default Proxy"?
