### ISSUE TITLE
Implement ProxyChecker

### ISSUE THREAD

**Issue by elfl0rd** [salarcode/SmartProxy#60]
If proxy not answer - disable it, and use another. (Easy automated mode)

**Comment by salarcode** [comment]
Implement ProxyChecker which checks proxy against certain site that user selects (the one he suspects that is blocked) Then mark the invalid proxies with a small Icon next to them.
Another option in settings (probably in the Subscription) called "Ignore dead proxies" to avoid the ones that are failed proxy test.

**Comment by salarcode** [comment]
Turns out that sending out request from an addon requires to have a privacy policy. Since this is proxy extension and has access to sensitive data I don't want cause doubt that this addon is collecting user data.

Another issue is that applying proxy to a specific request is not possible in JS but it can be made possible in addon but requires a lot of changes and carefully interpreting request for the desired ones. It doesn't really worth the effort.

**Comment by elfl0rd** [comment]
Sad :(
